### PR TITLE
chore(infra): upgrade project for 2020

### LINKED ISSUE #3: Buffer deprecated warning
I am developer from VS Code and we are using the module `yauzl v2.9.2` which depends on this module and it throws following warning.

```
internal/process/warning.js:127
      throw warning;
      ^

DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:156:11)
    at new Buffer (buffer.js:171:3)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/fd-slicer/index.js:109:18
    at pendGo (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/pend/index.js:54:3)
    at onCb (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/pend/index.js:41:7)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/fd-slicer/index.js:31:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) {
  name: 'DeprecationWarning',
  code: 'DEP0005'
}
```

https://github.com/thejoshwolfe/yauzl/issues/114
https://github.com/microsoft/vscode/issues/82524

### PR DESCRIPTION
**Pull request by AviVahl**
closes #2 
closes #3 

- fixed all Buffer deprecated warnings (also in tests).
- refactored code to use classes and other es2015 syntax (let/const; arrow functions; destructuring). Requires Node 8+.
- Travis now tests on existing node versions (8/10/12/13)
- use `npm test` in Travis (and removed `"test-travis"` script), as coveralls is not currently integrated (badge removed in previous commits).
- replaced deprecated `istanbul` with `nyc`. renamed script to `"coverage"`.
- ensure published package doesn't include `test` folder by defining `"files"` field in `package.json` (changelog/license/readme are always included)
- upgrade all dependencies to latest versions.
- adjusted git to ignore lock files and `nyc` output.

### CODE REVIEW

**Comment by AviVahl** [comment]
Hey @andrewrk, any chance you can review this? :)

**Comment by AviVahl** [comment]
ping @andrewrk 
would be awesome to get this in and released...

**Comment by andrewrk** [comment]
Fork it

**Comment by AviVahl** [comment]
Appreciate the response.
If project is unmaintained, please consider archiving repository and/or deprecating npm package (which has over 5 million weekly downloads).

**Comment by nalhabash** [comment]
@AviVahl looks very neat, will use some of that code in my fork 👍 
@andrewrk can you deprecate the npm package? 🙏

**Pull request closed without merging**
